services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - db
      - cache
  db:
    image: postgres
    environment:
      - POSTGRES_DB=usuarios
      - POSTGRES_USER=edu
      - POSTGRES_PASSWORD=0000
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cache:
    image: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
