services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app # Monta el directorio local ./app en /app dentro del contenedor para actualizar el código sin tener que reconstruir la imagen
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=usuarios
      - POSTGRES_USER=edu
      - POSTGRES_PASSWORD=0000
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
